#!/usr/bin/env bash
# Derive the git branching governance model from .aiflow/config.json -> .git.
# Writes .aiflow/branching.json (machine-readable, the §8 result), docs/branching.md
# (human-readable), ensures permanent branches exist, and seeds VERSION when releasing.
# Enforcement is done by the pre-push hook (reads branching.json). Idempotent.
set -uo pipefail
command -v jq >/dev/null 2>&1 || { echo "  ! jq required for branching model"; exit 0; }
CFG=".aiflow/config.json"; [ -f "$CFG" ] || exit 0
g() { jq -r "$1 // empty" "$CFG"; }

MODEL="$(g .git.model)"; [ -z "$MODEL" ] && MODEL=none
[ "$MODEL" = none ] && { rm -f .aiflow/branching.json; echo "  branching: none (no governance)"; exit 0; }
STRICT="$(g .git.strict)"; PRONLY="$(g .git.prOnly)"; AUTOREL="$(g .git.autoRelease)"
VER="$(g .git.versionStrategy)"; CHORE="$(g .git.chore)"
# null-check (not g()'s '// empty') so an explicit `releaseTags: false` survives the
# default - jq's // treats false itself as falsy and would collapse it (aiflow-5qe)
TAGS="$(jq -r 'if .git.releaseTags == null then true else .git.releaseTags end' "$CFG" 2>/dev/null || echo true)"
: "${STRICT:=false}"; : "${PRONLY:=false}"; : "${AUTOREL:=false}"; : "${CHORE:=false}"; : "${VER:=none}"

mkdir -p .aiflow docs
# ---- .aiflow/branching.json (governance descriptor) ----
jq -n --arg model "$MODEL" --argjson strict "$STRICT" --argjson prOnly "$PRONLY" \
  --argjson autoRel "$AUTOREL" --arg ver "$VER" --argjson tags "$TAGS" --argjson chore "$CHORE" '
{
  model: $model, strict: $strict,
  permanentBranches: ["main","develop"],
  branchTypes: ((if $model=="gitflow" then ["feature/*","bugfix/*","hotfix/*"] else [] end)
               + (if $chore then ["chore/*"] else [] end)),
  allowedCreations: ((if $model=="gitflow"
        then [{type:"feature/*",from:["develop"]},{type:"bugfix/*",from:["develop"]},{type:"hotfix/*",from:["main"]}]
        else [{type:"<any temporary>",from:["develop"]}] end)
      + (if $chore then [{type:"chore/*",from:["develop","main"]}] else [] end)),
  allowedMerges: ([{from:"develop",to:"main"},{from:"main",to:"develop"}]
      + (if $model=="gitflow" then [{from:"feature/*",to:"develop"},{from:"bugfix/*",to:"develop"},{from:"hotfix/*",to:"main"},{from:"hotfix/*",to:"develop"}] else [] end)
      + (if $chore then [{from:"chore/*",to:"develop"},{from:"chore/*",to:"main"}] else [] end)),
  mainRestricted: (if $model=="gitflow" then {onlyFrom:["develop","hotfix/*","chore/*"], forbidden:["feature/*","bugfix/*"]} else null end),
  pullRequests: (if $prOnly
      then {required:true, protectedBranches:["main","develop"],
            rules:["no direct push to protected branches","merge only via Pull Request","PR must pass validation"]}
      else {required:false} end),
  release: (if $autoRel
      then {auto:true, manualConfirm:true,
            triggers:["merge develop -> main (minor release, strips -SNAPSHOT)","merge hotfix/* -> main (patch release)"],
            excludesTrigger:["chore/* -> main"],
            versionStrategy:$ver,
            tag:{enabled:$tags, format:(if $ver=="calver" then "{version}" else "v{version}" end)}}
      else {auto:false} end),
  branchNaming: (if ($model=="gitflow" and $strict) then "enforced" else "not enforced (temporary branches may use any name)" end)
}' > .aiflow/branching.json
echo "  branching: $MODEL (strict=$STRICT prOnly=$PRONLY autoRelease=$AUTOREL ver=$VER chore=$CHORE) -> .aiflow/branching.json"

# ---- docs/branching.md (human-readable) ----
{
  echo "# Branching model: $MODEL"
  echo
  echo "Generated by aiflow from .aiflow/config.json. Change via \`aiflow change-settings\`."
  echo
  echo "- **Permanent branches:** main, develop"
  echo "- **The mainline is named \`main\`** — not \`master\`. Every rule below, the pre-push hook,"
  echo "  \`aiflow release\` and \`aiflow hotfix\` reference \`main\` by name. A repo still on \`master\`"
  echo "  is renamed by \`aiflow apply\` (\`git branch -m master main\`); push it and switch the"
  echo "  default branch on your remote, then delete the old \`master\`."
  echo "- **Strict rules:** $STRICT   **PR-only:** $PRONLY   **Auto-release:** $AUTOREL   **chore/*:** $CHORE"
  [ "$AUTOREL" = true ] && echo "- **Versioning:** $VER   **Release tags:** $TAGS"
  echo
  echo "## Allowed branch creation"
  jq -r '.allowedCreations[] | "- \(.type) ← from: \(.from|join(", "))"' .aiflow/branching.json
  echo
  echo "## Allowed merges"
  jq -r '.allowedMerges[] | "- \(.from) → \(.to)"' .aiflow/branching.json
  echo
  if [ "$MODEL" = gitflow ]; then
    echo "## main is restricted"
    echo "- Only \`chore/*\` and \`hotfix/*\` may ever target \`main\`."
    echo "- \`feature/*\` and \`bugfix/*\` always target \`develop\` — never \`main\`, directly or via PR."
    echo "- Doc-only changes and CI/workflow-file-only changes (\`.github/workflows/**\`) count as \`chore/*\`, not \`feature/*\`."
    echo
  fi
  if [ "$PRONLY" = true ]; then
    echo "## Pull requests"
    echo "- No direct push to main/develop; merge only via PR; PR must pass validation."
    echo
  fi
  if [ "$AUTOREL" = true ]; then
    echo "## Releases"
    echo "- A merge of \`develop\` → \`main\` **or** \`hotfix/*\` → \`main\` creates a release (\`aiflow release\`)."
    echo "- A merge of \`chore/*\` → \`main\` never triggers a release."
    echo "- **Releasing is never automatic** — always ask the user before running \`aiflow release\` / merging into main."
    if [ "$VER" = calver ]; then
      echo "- **CalVer** \`YYYY.MM\`: release uses the current calendar version; develop is bumped to the next."
    else
      echo "- **SemVer** \`MAJOR.MINOR.PATCH\`, in-progress work always carries a suffix; \`main\` never does:"
      echo "  - develop carries \`X.Y.0-SNAPSHOT\`; on release → \`X.Y.0\` (minor release)."
      echo "  - \`aiflow hotfix <name>\` branches off main and bumps to \`X.Y.(Z+1)-HOTFIX\`; on release → \`X.Y.(Z+1)\` (patch release)."
      echo "  - either way, develop is then bumped to \`X.(Y+1).0-SNAPSHOT\`, and hotfix commits are also merged into develop so the fix isn't lost."
      echo "  - a pre-push guard rejects any push to \`main\` whose \`VERSION\` still ends in \`-SNAPSHOT\`/\`-HOTFIX\`."
    fi
    [ "$TAGS" = true ] && echo "- A git tag is created on each release ($([ "$VER" = calver ] && echo '{version}' || echo 'v{version}'))."
    echo
  fi
  echo "Enforced locally by the \`pre-push\` git hook; enforce on the server with branch protection (\`aiflow protect\`)."
} > docs/branching.md

# ---- legacy 'master' -> 'main' (aiflow-dpz) ----
# The whole governance below hard-codes 'main'. A repo sitting on 'master' would keep it as the
# active branch while we additionally branch 'main' off HEAD - two divergent lines, and every
# rule silently stops applying. So rename when it is unambiguous, and refuse when it is not.
if [ -d .git ] && git rev-parse --verify HEAD >/dev/null 2>&1; then
  HAS_MASTER=0; HAS_MAIN=0
  git show-ref --verify --quiet refs/heads/master && HAS_MASTER=1
  git show-ref --verify --quiet refs/heads/main   && HAS_MAIN=1
  if [ "$HAS_MASTER" = 1 ] && [ "$HAS_MAIN" = 1 ]; then
    echo "  ! both 'master' and 'main' exist - aiflow governs 'main' only and will NOT touch 'master'."
    echo "    Merge or delete 'master' yourself, then re-run 'aiflow apply'."
  elif [ "$HAS_MASTER" = 1 ] && [ "${AIFLOW_NO_BRANCH_RENAME:-0}" = 1 ]; then
    echo "  ! branch is 'master' but AIFLOW_NO_BRANCH_RENAME=1 - governance expects 'main' and will not apply."
  elif [ "$HAS_MASTER" = 1 ]; then
    if git branch -m master main 2>/dev/null; then
      echo "  renamed branch master -> main (aiflow's branching model governs 'main')"
      if git remote get-url origin >/dev/null 2>&1; then
        echo "    remote still has 'master'. Finish the migration yourself:"
        echo "      git push -u origin main"
        echo "      # switch the default branch to 'main' in your host's settings, then:"
        echo "      git push origin --delete master"
      fi
    else
      echo "  ! could not rename 'master' -> 'main' - do it manually: git branch -m master main"
    fi
  fi
fi

# ---- ensure permanent branches exist (don't switch) ----
# If a remote-tracking ref already exists (origin/$b) but no local branch, create the local
# branch FROM origin/$b, not from current HEAD - origin/$b may have diverged from wherever
# you're currently checked out, and branching off HEAD would silently lose/ignore that history.
if [ -d .git ] && git rev-parse --verify HEAD >/dev/null 2>&1; then
  for b in main develop; do
    if ! git show-ref --verify --quiet "refs/heads/$b"; then
      if git show-ref --verify --quiet "refs/remotes/origin/$b"; then
        git branch "$b" "origin/$b" >/dev/null 2>&1 && echo "  created branch $b (tracking origin/$b)"
      else
        git branch "$b" >/dev/null 2>&1 && echo "  created branch $b"
      fi
    fi
  done
fi

# ---- seed VERSION for releases ----
if [ "$AUTOREL" = true ] && [ ! -f VERSION ]; then
  if [ "$VER" = calver ]; then date +%Y.%m > VERSION; else echo "0.1.0-SNAPSHOT" > VERSION; fi
  echo "  seeded VERSION ($(cat VERSION))"
fi
