#!/usr/bin/env bash
# Derive the git branching governance model from .aiflow/config.json -> .git.
# Writes .aiflow/branching.json (machine-readable, the §8 result), docs/branching.md
# (human-readable), ensures permanent branches exist, and seeds VERSION when releasing.
# Enforcement is done by the pre-push hook (reads branching.json). Idempotent.
set -uo pipefail
command -v jq >/dev/null 2>&1 || { echo "  ! jq required for branching model"; exit 0; }
CFG=".aiflow/config.json"; [ -f "$CFG" ] || exit 0
g() { jq -r "$1 // empty" "$CFG"; }

MODEL="$(g .git.model)"; [ -z "$MODEL" ] && MODEL=none
[ "$MODEL" = none ] && { rm -f .aiflow/branching.json; echo "  branching: none (no governance)"; exit 0; }
STRICT="$(g .git.strict)"; PRONLY="$(g .git.prOnly)"; AUTOREL="$(g .git.autoRelease)"
VER="$(g .git.versionStrategy)"; TAGS="$(g .git.releaseTags)"; CHORE="$(g .git.chore)"
: "${STRICT:=false}"; : "${PRONLY:=false}"; : "${AUTOREL:=false}"; : "${TAGS:=true}"; : "${CHORE:=false}"; : "${VER:=none}"

mkdir -p .aiflow docs
# ---- .aiflow/branching.json (governance descriptor) ----
jq -n --arg model "$MODEL" --argjson strict "$STRICT" --argjson prOnly "$PRONLY" \
  --argjson autoRel "$AUTOREL" --arg ver "$VER" --argjson tags "$TAGS" --argjson chore "$CHORE" '
{
  model: $model, strict: $strict,
  permanentBranches: ["main","develop"],
  branchTypes: ((if $model=="gitflow" then ["feature/*","hotfix/*"] else [] end)
               + (if $chore then ["chore/*"] else [] end)),
  allowedCreations: ((if $model=="gitflow"
        then [{type:"feature/*",from:["develop"]},{type:"hotfix/*",from:["main"]}]
        else [{type:"<any temporary>",from:["develop"]}] end)
      + (if $chore then [{type:"chore/*",from:["develop","main"]}] else [] end)),
  allowedMerges: ([{from:"develop",to:"main"},{from:"main",to:"develop"}]
      + (if $model=="gitflow" then [{from:"feature/*",to:"develop"},{from:"hotfix/*",to:"main"}] else [] end)
      + (if $chore then [{from:"chore/*",to:"develop"},{from:"chore/*",to:"main"}] else [] end)),
  pullRequests: (if $prOnly
      then {required:true, protectedBranches:["main","develop"],
            rules:["no direct push to protected branches","merge only via Pull Request","PR must pass validation"]}
      else {required:false} end),
  release: (if $autoRel
      then {auto:true, trigger:"merge develop -> main", versionStrategy:$ver,
            tag:{enabled:$tags, format:(if $ver=="calver" then "{version}" else "v{version}" end)}}
      else {auto:false} end),
  branchNaming: (if ($model=="gitflow" and $strict) then "enforced" else "not enforced (temporary branches may use any name)" end)
}' > .aiflow/branching.json
echo "  branching: $MODEL (strict=$STRICT prOnly=$PRONLY autoRelease=$AUTOREL ver=$VER chore=$CHORE) -> .aiflow/branching.json"

# ---- docs/branching.md (human-readable) ----
{
  echo "# Branching model: $MODEL"
  echo
  echo "Generated by aiflow from .aiflow/config.json. Change via \`aiflow change-settings\`."
  echo
  echo "- **Permanent branches:** main, develop"
  echo "- **Strict rules:** $STRICT   **PR-only:** $PRONLY   **Auto-release:** $AUTOREL   **chore/*:** $CHORE"
  [ "$AUTOREL" = true ] && echo "- **Versioning:** $VER   **Release tags:** $TAGS"
  echo
  echo "## Allowed branch creation"
  jq -r '.allowedCreations[] | "- \(.type) ← from: \(.from|join(", "))"' .aiflow/branching.json
  echo
  echo "## Allowed merges"
  jq -r '.allowedMerges[] | "- \(.from) → \(.to)"' .aiflow/branching.json
  echo
  if [ "$PRONLY" = true ]; then
    echo "## Pull requests"
    echo "- No direct push to main/develop; merge only via PR; PR must pass validation."
    echo
  fi
  if [ "$AUTOREL" = true ]; then
    echo "## Releases"
    echo "- A merge of develop → main creates a release (\`aiflow release\`)."
    if [ "$VER" = calver ]; then
      echo "- **CalVer** \`YYYY.MM\`: release uses the current calendar version; develop is bumped to the next."
    else
      echo "- **SemVer** \`MAJOR.MINOR.PATCH\`: \`X.Y.0-SNAPSHOT\` → \`X.Y.0\` on release; develop bumps to \`X.(Y+1).0-SNAPSHOT\`."
    fi
    [ "$TAGS" = true ] && echo "- A git tag is created on each release ($([ "$VER" = calver ] && echo '{version}' || echo 'v{version}'))."
    echo
  fi
  echo "Enforced locally by the \`pre-push\` git hook; enforce on the server with branch protection (\`aiflow protect\`)."
} > docs/branching.md

# ---- ensure permanent branches exist (don't switch) ----
if [ -d .git ] && git rev-parse --verify HEAD >/dev/null 2>&1; then
  for b in main develop; do
    git show-ref --verify --quiet "refs/heads/$b" || { git branch "$b" >/dev/null 2>&1 && echo "  created branch $b"; }
  done
fi

# ---- seed VERSION for releases ----
if [ "$AUTOREL" = true ] && [ ! -f VERSION ]; then
  if [ "$VER" = calver ]; then date +%Y.%m > VERSION; else echo "0.1.0-SNAPSHOT" > VERSION; fi
  echo "  seeded VERSION ($(cat VERSION))"
fi
